services:
  - type: web
    name: web-scraper-backend
    env: docker
    repo: https://github.com/leonardolopezcallejo/web-scraper
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    buildFilter:
      paths:
        - app/**/*
        - Dockerfile

  - type: web
    name: web-scraper-frontend
    repo: https://github.com/leonardolopezcallejo/web-scraper
    branch: main
    buildCommand: ""
    staticPublishPath: frontend
    autoDeploy: true
    buildFilter:
      paths:
        - frontend/**/*
